version: "3.9"

services:
  server:
    build: .
    container_name: ${SERVER_CONTAINER_NAME}
    ports:
      - target: ${SERVER_TARGET_PORT}
        published: ${SERVER_PUBLISHED_PORT}
    volumes:
      - type: bind
        source: ${SERVER_STATIC_MOUNTPOINT}
        target: /app/static
    depends_on:
      - mariadb
      - redis
    entrypoint: [ "/app/wait-for-it.sh", "mariadb:3306", "-s", "--",
                  "/app/wait-for-it.sh", "redis:6379", "-s", "--",
                  "sh", "-c", "java ${JAVA_OPTS} -jar /app/app.jar" ]

  mariadb:
    image: "mariadb:10.5"
    container_name: ${MARIADB_CONTAINER_NAME}
    volumes:
      - type: bind
        source: ${MARIADB_DATA_MOUNTPOINT}
        target: /var/lib/mysql

  redis:
    image: "redis:6.2"
    container_name: ${REDIS_CONTAINER_NAME}
    volumes:
      - type: bind
        source: ${REDIS_CONF_MOUNTPOINT}
        target: /etc/redis
      - type: bind
        source: ${REDIS_DATA_MOUNTPOINT}
        target: /data
    entrypoint: [ "redis-server", "/etc/redis/redis.conf" ]